server:
  port: 9001
  
spring:
  application:
    name: masterdata-service
#  datasource:
#    url: jdbc:mysql://localhost:3306/advcatedb
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#  jpa:
#   hibernate.ddl-auto: update
#   properties:
#     hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect    
  config:
    import:
     configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
  zipkin:
    base-url: http://localhost:9411      
  data:
      mongodb:        port: 27017        database: advcatedb         host: localhost
management:
   endpoints:
    web: 
     exposure:
       include: "*"
   health:
    circuitbreakers:
      enabled: true 
   endpoint:
    health:
      show-details: always        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  
  instance:
    prefer-ip-address: true  
   
      
    
   